export const GET_BLOGS_REQUEST = "GET_BLOGS_REQUEST";
export const GET_BLOGS_SUCCESS = "GET_BLOGS_SUCCESS";
export const GET_BLOGS_FAILURE = "GET_BLOGS_FAILURE";
export const GET_OWN_BLOGS = "GET_OWN_BLOGS"; // not yet needed
export const BLOG_CREATING = "ADD_BLOG";
export const BLOG_CREATE_SUCCESS = "BLOG_CREATE_SUCCESS";
export const BLOG_CREATE_ERROR = "BLOG_CREATE_ERROR";
export const BLOG_REQUESTING = "BLOG_REQUESTING";
export const BLOG_REQUEST_SUCCESS = "BLOG_REQUEST_SUCCESS";
export const BLOG_REQUEST_ERROR = "BLOG_REQUEST_ERROR";

export const CHANGE_USERID = "CHANGE_USERID";

export const CHANGE_SELECTED_LOCATION = "CHANGE_SELECTED_LOCATION";

export const GET_POINTS_OF_INTEREST_SUCCESS = "GET_POINTS_OF_INTEREST_SUCCESS";
export const GET_ATTRACTIONS_SUCCESS = "GET_ATTRACTIONS_SUCCESS";
export const GET_BASIC_LOCATION_INFO_SUCCESS = "GET_BASIC_LOCATION_INFO_SUCCESS";

export const ADD_FAV_DESTINATION_SUCCESS = "ADD_FAV_DESTINATION_SUCCESS";
export const GET_FAV_DESTINATIONS_SUCCESS = "GET_FAV_DESTINATIONS_SUCCESS";
// export const DELETE_FAV_DESTINATION_SUCCESS = "DELETE_FAV_DESTINATION_SUCCESS";

export const ADD_VISITED_DESTINATION_SUCCESS = "ADD_VISITED_DESTINATION_SUCCESS";
export const GET_VISITED_DESTINATIONS_SUCCESS = "GET_VISITED_DESTINATIONS_SUCCESS";
// export const DELETE_VISITED_DESTINATION_SUCCESS = "DELETE_VISITED_DESTINATION_SUCCESS";

export const SET_HEADER = "SET_HEADER";
export const RCV_ERROR = "RCV_ERROR";
export const ADD_ERROR = "ADD_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const CLIENT_SET = "CLIENT_SET";
export const CLIENT_UNSET = "CLIENT_UNSET";

export const SIGNUP_REQUESTING = "SIGNUP_REQUESTING";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const LOGIN_REQUESTING = "LOGIN_REQUESTING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
